# Generated by Django 5.2.3 on 2025-06-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('valor_pecas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor das Peças')),
                ('valor_mao_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Mão de Obra')),
                ('valor_galho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Galho')),
                ('data_da_entrada', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('data_da_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_de_servico', to='core.cliente')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_de_servico', to='core.produto')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_da_entrada'],
            },
        ),
    ]
